# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.hostname = "DEV"
  config.vm.network :private_network, ip: "10.10.0.100"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = 1
  end
  config.vm.provision "shell", inline: <<-SHELL  
     apt-get update
     apt-get intall php libapache2-mod-php-mcrypt php-mysql
     apt-get install -y apache2
     apt-get install mysql-server
     apt-get install python3
     apt-get install python3-pip
  SHELL
end
